#![deny(unsafe_code)]

//! Fault-Tolerant Surface Code Patch & Stabilizer Syndrome Decoder.
//!
//! Models rotated planar surface code patches of distance d = 3 (9 data qubits, 8 ancillas)
//! and distance d = 5 (25 data qubits, 24 ancillas).
//! Implements Star (X-type) and Plaquette (Z-type) stabilizer checks, verifies
//! stabilizer commutation [A_s, B_p] = 0, injects physical Pauli errors,
//! extracts syndrome defect graphs, and applies Minimum-Weight Perfect Matching (MWPM)
//! and greedy clustering decoders to demonstrate threshold scaling P_L << P_phys.

/// Lightweight deterministic pseudo-random number generator for syndrome simulation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SurfaceRng {
    state: u64,
}

impl SurfaceRng {
    /// Creates a new RNG with given 64-bit seed.
    pub fn new(seed: u64) -> Self {
        Self {
            state: if seed == 0 { 0x5a17_d83e_f12c_49b6 } else { seed },
        }
    }

    /// Generates next pseudo-random u64.
    pub fn next_u64(&mut self) -> u64 {
        let mut x = self.state;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.state = x;
        x
    }

    /// Generates next pseudo-random f64 in [0.0, 1.0).
    pub fn next_f64(&mut self) -> f64 {
        (self.next_u64() >> 11) as f64 / (1u64 << 53) as f64
    }
}

/// Type of stabilizer operator in the rotated surface code patch.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SurfaceStabilizerKind {
    /// Star X-stabilizer: A_s = prod_{i in s} X_i (measures Z phase errors).
    StarX,
    /// Plaquette Z-stabilizer: B_p = prod_{j in p} Z_j (measures X bit-flip errors).
    PlaquetteZ,
}

/// Pauli error operator acting on a data qubit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PauliOperator {
    Identity,
    PauliX,
    PauliY,
    PauliZ,
}

impl PauliOperator {
    /// Multiplies two Pauli operators (ignoring global phase +/- 1 or +/- i).
    pub fn compose(self, rhs: Self) -> Self {
        match (self, rhs) {
            (Self::Identity, other) | (other, Self::Identity) => other,
            (Self::PauliX, Self::PauliX) => Self::Identity,
            (Self::PauliZ, Self::PauliZ) => Self::Identity,
            (Self::PauliY, Self::PauliY) => Self::Identity,
            (Self::PauliX, Self::PauliZ) | (Self::PauliZ, Self::PauliX) => Self::PauliY,
            (Self::PauliX, Self::PauliY) | (Self::PauliY, Self::PauliX) => Self::PauliZ,
            (Self::PauliY, Self::PauliZ) | (Self::PauliZ, Self::PauliY) => Self::PauliX,
        }
    }

    /// Checks if this Pauli anticommutes with an X operator (i.e. if it has a Z or Y component).
    pub fn anticommutes_with_x(self) -> bool {
        matches!(self, Self::PauliZ | Self::PauliY)
    }

    /// Checks if this Pauli anticommutes with a Z operator (i.e. if it has an X or Y component).
    pub fn anticommutes_with_z(self) -> bool {
        matches!(self, Self::PauliX | Self::PauliY)
    }
}

/// A stabilizer check measurement on the surface code.
#[derive(Debug, Clone, PartialEq)]
pub struct SurfaceStabilizerCheck {
    pub id: usize,
    pub kind: SurfaceStabilizerKind,
    pub data_qubits: Vec<usize>,
    pub center_x: f64,
    pub center_y: f64,
    pub label: String,
}

/// Distance configuration for the surface code patch.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CodeDistance {
    Distance3,
    Distance5,
}

impl CodeDistance {
    pub fn value(self) -> usize {
        match self {
            Self::Distance3 => 3,
            Self::Distance5 => 5,
        }
    }

    pub fn num_data_qubits(self) -> usize {
        match self {
            Self::Distance3 => 9,
            Self::Distance5 => 25,
        }
    }

    pub fn num_ancilla_checks(self) -> usize {
        match self {
            Self::Distance3 => 8,
            Self::Distance5 => 24,
        }
    }
}

/// Syndrome defect extraction result.
#[derive(Debug, Clone, PartialEq)]
pub struct SyndromeExtractionResult {
    /// Eigenvalue of each stabilizer check (+1 for clean, -1 for detected defect).
    pub eigenvalues: Vec<i8>,
    /// IDs of stabilizer checks flagging a defect (-1).
    pub defect_check_ids: Vec<usize>,
    /// Number of active defects.
    pub defect_count: usize,
    /// Physical Pauli errors injected on each data qubit.
    pub injected_errors: Vec<PauliOperator>,
}

/// Error recovery result generated by the decoder.
#[derive(Debug, Clone, PartialEq)]
pub struct RecoveryResult {
    /// Correction Pauli operators applied to each data qubit.
    pub corrections: Vec<PauliOperator>,
    /// True if all stabilizer syndromes are returned to +1.
    pub syndromes_cleared: bool,
    /// True if the correction restored the logical state without a logical Pauli flip.
    pub logical_success: bool,
    /// Residual logical operator after correction (Identity = success).
    pub logical_residual: PauliOperator,
}

/// Surface code threshold point for plotting threshold curves.
#[derive(Debug, Clone, PartialEq)]
pub struct ThresholdCurvePoint {
    pub physical_error_rate: f64,
    pub logical_error_d3: f64,
    pub logical_error_d5: f64,
}

/// Surface code patch and stabilizer engine.
#[derive(Debug, Clone, PartialEq)]
pub struct SurfaceCodePatch {
    pub distance: CodeDistance,
    pub checks: Vec<SurfaceStabilizerCheck>,
    pub data_qubit_coords: Vec<(f64, f64)>,
}

impl SurfaceCodePatch {
    /// Constructs a rotated planar surface code patch of distance d = 3 or d = 5.
    pub fn new(distance: CodeDistance) -> Self {
        match distance {
            CodeDistance::Distance3 => Self::build_distance_3(),
            CodeDistance::Distance5 => Self::build_distance_5(),
        }
    }

    fn build_distance_3() -> Self {
        // 3x3 grid of 9 data qubits: indices 0..8
        // Qubit coords: (r, c) where r in 0..3, c in 0..3
        let mut coords = Vec::with_capacity(9);
        for r in 0..3 {
            for c in 0..3 {
                coords.push((c as f64 * 2.0, r as f64 * 2.0));
            }
        }

        // 8 ancillas: 4 Star X-checks (green), 4 Plaquette Z-checks (blue)
        let mut checks = Vec::with_capacity(8);

        // Star X checks (detect Z errors)
        // Check 0: top boundary (qubits 0, 1)
        checks.push(SurfaceStabilizerCheck {
            id: 0,
            kind: SurfaceStabilizerKind::StarX,
            data_qubits: vec![0, 1],
            center_x: 1.0,
            center_y: -0.8,
            label: "X_top".to_string(),
        });
        // Check 1: bulk star (qubits 1, 2, 4, 5)
        checks.push(SurfaceStabilizerCheck {
            id: 1,
            kind: SurfaceStabilizerKind::StarX,
            data_qubits: vec![1, 2, 4, 5],
            center_x: 3.0,
            center_y: 1.0,
            label: "X_bulk1".to_string(),
        });
        // Check 2: bulk star (qubits 3, 4, 6, 7)
        checks.push(SurfaceStabilizerCheck {
            id: 2,
            kind: SurfaceStabilizerKind::StarX,
            data_qubits: vec![3, 4, 6, 7],
            center_x: 1.0,
            center_y: 3.0,
            label: "X_bulk2".to_string(),
        });
        // Check 3: bottom boundary (qubits 7, 8)
        checks.push(SurfaceStabilizerCheck {
            id: 3,
            kind: SurfaceStabilizerKind::StarX,
            data_qubits: vec![7, 8],
            center_x: 3.0,
            center_y: 4.8,
            label: "X_bot".to_string(),
        });

        // Plaquette Z checks (detect X errors)
        // Check 4: left boundary (qubits 3, 6)
        checks.push(SurfaceStabilizerCheck {
            id: 4,
            kind: SurfaceStabilizerKind::PlaquetteZ,
            data_qubits: vec![3, 6],
            center_x: -0.8,
            center_y: 3.0,
            label: "Z_left".to_string(),
        });
        // Check 5: bulk plaquette (qubits 0, 1, 3, 4)
        checks.push(SurfaceStabilizerCheck {
            id: 5,
            kind: SurfaceStabilizerKind::PlaquetteZ,
            data_qubits: vec![0, 1, 3, 4],
            center_x: 1.0,
            center_y: 1.0,
            label: "Z_bulk1".to_string(),
        });
        // Check 6: bulk plaquette (qubits 4, 5, 7, 8)
        checks.push(SurfaceStabilizerCheck {
            id: 6,
            kind: SurfaceStabilizerKind::PlaquetteZ,
            data_qubits: vec![4, 5, 7, 8],
            center_x: 3.0,
            center_y: 3.0,
            label: "Z_bulk2".to_string(),
        });
        // Check 7: right boundary (qubits 2, 5)
        checks.push(SurfaceStabilizerCheck {
            id: 7,
            kind: SurfaceStabilizerKind::PlaquetteZ,
            data_qubits: vec![2, 5],
            center_x: 4.8,
            center_y: 1.0,
            label: "Z_right".to_string(),
        });

        Self {
            distance: CodeDistance::Distance3,
            checks,
            data_qubit_coords: coords,
        }
    }

    fn build_distance_5() -> Self {
        // 5x5 grid of 25 data qubits
        let mut coords = Vec::with_capacity(25);
        for r in 0..5 {
            for c in 0..5 {
                coords.push((c as f64 * 2.0, r as f64 * 2.0));
            }
        }

        // 24 ancillas: 12 Star X, 12 Plaquette Z
        let mut checks = Vec::with_capacity(24);
        let mut id = 0;

        // 8 bulk X checks (r + c odd)
        let bulk_x = [
            (vec![1, 2, 6, 7], 3.0, 1.0),
            (vec![3, 4, 8, 9], 7.0, 1.0),
            (vec![5, 6, 10, 11], 1.0, 3.0),
            (vec![7, 8, 12, 13], 5.0, 3.0),
            (vec![11, 12, 16, 17], 3.0, 5.0),
            (vec![13, 14, 18, 19], 7.0, 5.0),
            (vec![15, 16, 20, 21], 1.0, 7.0),
            (vec![17, 18, 22, 23], 5.0, 7.0),
        ];
        for (q, cx, cy) in bulk_x {
            checks.push(SurfaceStabilizerCheck {
                id,
                kind: SurfaceStabilizerKind::StarX,
                data_qubits: q,
                center_x: cx,
                center_y: cy,
                label: format!("X_bulk_{}", id),
            });
            id += 1;
        }

        // 4 boundary X checks (top and bottom)
        let bound_x = [
            (vec![0, 1], 1.0, -0.8),
            (vec![2, 3], 5.0, -0.8),
            (vec![21, 22], 3.0, 8.8),
            (vec![23, 24], 7.0, 8.8),
        ];
        for (q, cx, cy) in bound_x {
            checks.push(SurfaceStabilizerCheck {
                id,
                kind: SurfaceStabilizerKind::StarX,
                data_qubits: q,
                center_x: cx,
                center_y: cy,
                label: format!("X_bound_{}", id),
            });
            id += 1;
        }

        // 8 bulk Z checks (r + c even)
        let bulk_z = [
            (vec![0, 1, 5, 6], 1.0, 1.0),
            (vec![2, 3, 7, 8], 5.0, 1.0),
            (vec![6, 7, 11, 12], 3.0, 3.0),
            (vec![8, 9, 13, 14], 7.0, 3.0),
            (vec![10, 11, 15, 16], 1.0, 5.0),
            (vec![12, 13, 17, 18], 5.0, 5.0),
            (vec![16, 17, 21, 22], 3.0, 7.0),
            (vec![18, 19, 23, 24], 7.0, 7.0),
        ];
        for (q, cx, cy) in bulk_z {
            checks.push(SurfaceStabilizerCheck {
                id,
                kind: SurfaceStabilizerKind::PlaquetteZ,
                data_qubits: q,
                center_x: cx,
                center_y: cy,
                label: format!("Z_bulk_{}", id),
            });
            id += 1;
        }

        // 4 boundary Z checks (left and right)
        let bound_z = [
            (vec![5, 10], -0.8, 3.0),
            (vec![15, 20], -0.8, 7.0),
            (vec![4, 9], 8.8, 1.0),
            (vec![14, 19], 8.8, 5.0),
        ];
        for (q, cx, cy) in bound_z {
            checks.push(SurfaceStabilizerCheck {
                id,
                kind: SurfaceStabilizerKind::PlaquetteZ,
                data_qubits: q,
                center_x: cx,
                center_y: cy,
                label: format!("Z_bound_{}", id),
            });
            id += 1;
        }

        Self {
            distance: CodeDistance::Distance5,
            checks,
            data_qubit_coords: coords,
        }
    }

    /// Verifies that all Star X-stabilizers commute with all Plaquette Z-stabilizers.
    /// In a valid surface code, any Star and Plaquette overlap on an even number of qubits (0 or 2),
    /// guaranteeing [A_s, B_p] = 0.
    pub fn verify_stabilizer_commutativity(&self) -> (bool, usize) {
        let x_checks: Vec<_> = self
            .checks
            .iter()
            .filter(|c| c.kind == SurfaceStabilizerKind::StarX)
            .collect();
        let z_checks: Vec<_> = self
            .checks
            .iter()
            .filter(|c| c.kind == SurfaceStabilizerKind::PlaquetteZ)
            .collect();

        let mut all_commute = true;
        let mut total_pairs = 0;

        for x in &x_checks {
            for z in &z_checks {
                total_pairs += 1;
                let overlap_count = x
                    .data_qubits
                    .iter()
                    .filter(|q| z.data_qubits.contains(q))
                    .count();
                // Overlap must be even (0 or 2) for Pauli operators to commute
                if overlap_count % 2 != 0 {
                    all_commute = false;
                }
            }
        }

        (all_commute, total_pairs)
    }

    /// Simulates random physical Pauli errors on data qubits with physical error rate p.
    pub fn inject_random_errors(&self, p_error: f64, rng: &mut SurfaceRng) -> Vec<PauliOperator> {
        let mut errors = vec![PauliOperator::Identity; self.distance.num_data_qubits()];
        for err in &mut errors {
            let r = rng.next_f64();
            if r < p_error {
                // Depolarizing channel: 1/3 X, 1/3 Y, 1/3 Z
                let sub = rng.next_f64();
                *err = if sub < 0.333 {
                    PauliOperator::PauliX
                } else if sub < 0.666 {
                    PauliOperator::PauliZ
                } else {
                    PauliOperator::PauliY
                };
            }
        }
        errors
    }

    /// Extracts syndrome defects for given physical errors on data qubits.
    pub fn extract_syndromes(
        &self,
        errors: &[PauliOperator],
        syndrome_measurement_noise: f64,
        rng: &mut SurfaceRng,
    ) -> SyndromeExtractionResult {
        let mut eigenvalues = Vec::with_capacity(self.checks.len());
        let mut defect_check_ids = Vec::new();

        for check in &self.checks {
            let mut anticommuting_flips = 0;
            for &q in &check.data_qubits {
                if q < errors.len() {
                    let err = errors[q];
                    match check.kind {
                        SurfaceStabilizerKind::StarX => {
                            // Star X measures Z errors (anticommutes with Z or Y)
                            if err.anticommutes_with_x() {
                                anticommuting_flips += 1;
                            }
                        }
                        SurfaceStabilizerKind::PlaquetteZ => {
                            // Plaquette Z measures X errors (anticommutes with X or Y)
                            if err.anticommutes_with_z() {
                                anticommuting_flips += 1;
                            }
                        }
                    }
                }
            }

            let mut eigenvalue = if anticommuting_flips % 2 == 0 { 1i8 } else { -1i8 };

            // Apply syndrome measurement bit-flip noise if configured
            if syndrome_measurement_noise > 0.0 && rng.next_f64() < syndrome_measurement_noise {
                eigenvalue = -eigenvalue;
            }

            if eigenvalue == -1 {
                defect_check_ids.push(check.id);
            }
            eigenvalues.push(eigenvalue);
        }

        let defect_count = defect_check_ids.len();
        SyndromeExtractionResult {
            eigenvalues,
            defect_check_ids,
            defect_count,
            injected_errors: errors.to_vec(),
        }
    }

    /// Decodes the syndrome using a fast greedy clustering / Minimum-Weight Perfect Matching (MWPM)
    /// algorithm to determine Pauli corrections.
    pub fn decode_and_correct(
        &self,
        syndrome: &SyndromeExtractionResult,
    ) -> RecoveryResult {
        let num_q = self.distance.num_data_qubits();
        let mut corrections = vec![PauliOperator::Identity; num_q];

        // Process X-type defects (fixing Z errors) and Z-type defects (fixing X errors) separately
        let mut x_defects = Vec::new();
        let mut z_defects = Vec::new();

        for &id in &syndrome.defect_check_ids {
            if let Some(c) = self.checks.iter().find(|chk| chk.id == id) {
                match c.kind {
                    SurfaceStabilizerKind::StarX => x_defects.push(c),
                    SurfaceStabilizerKind::PlaquetteZ => z_defects.push(c),
                }
            }
        }

        // Pair up X-defects and apply Z corrections along connecting data qubits
        self.match_and_correct_defects(
            &x_defects,
            PauliOperator::PauliZ,
            &mut corrections,
        );

        // Pair up Z-defects and apply X corrections along connecting data qubits
        self.match_and_correct_defects(
            &z_defects,
            PauliOperator::PauliX,
            &mut corrections,
        );

        // Compute net residual on each qubit: residual = injected * correction
        let mut residuals = Vec::with_capacity(num_q);
        for i in 0..num_q {
            let inj = syndrome.injected_errors.get(i).copied().unwrap_or(PauliOperator::Identity);
            let cor = corrections[i];
            residuals.push(inj.compose(cor));
        }

        // Check if residual errors clear all syndromes
        let post_syndrome = self.extract_syndromes(&residuals, 0.0, &mut SurfaceRng::new(1234));
        let syndromes_cleared = post_syndrome.defect_count == 0;

        // Check logical operator commutation:
        // Logical X_L is a horizontal chain across row 0 (qubits 0, 1, 2 for d=3)
        // Logical Z_L is a vertical chain along column 0 (qubits 0, 3, 6 for d=3)
        let d = self.distance.value();
        let mut x_l_flips = 0;
        let mut z_l_flips = 0;

        for c in 0..d {
            let q_x = c; // Row 0
            if q_x < residuals.len() && residuals[q_x].anticommutes_with_x() {
                x_l_flips += 1;
            }
        }
        for r in 0..d {
            let q_z = r * d; // Col 0
            if q_z < residuals.len() && residuals[q_z].anticommutes_with_z() {
                z_l_flips += 1;
            }
        }

        let logical_flip_x = x_l_flips % 2 != 0;
        let logical_flip_z = z_l_flips % 2 != 0;

        let logical_residual = match (logical_flip_x, logical_flip_z) {
            (false, false) => PauliOperator::Identity,
            (true, false) => PauliOperator::PauliZ,
            (false, true) => PauliOperator::PauliX,
            (true, true) => PauliOperator::PauliY,
        };

        let logical_success = syndromes_cleared && (logical_residual == PauliOperator::Identity);

        RecoveryResult {
            corrections,
            syndromes_cleared,
            logical_success,
            logical_residual,
        }
    }

    fn match_and_correct_defects(
        &self,
        defects: &[&SurfaceStabilizerCheck],
        correction_pauli: PauliOperator,
        corrections: &mut [PauliOperator],
    ) {
        if defects.is_empty() {
            return;
        }

        let mut remaining = defects.to_vec();

        while remaining.len() >= 2 {
            let d1 = remaining.remove(0);
            // Find closest neighbor in remaining
            let mut best_idx = 0;
            let mut best_dist = f64::MAX;
            for (idx, candidate) in remaining.iter().enumerate() {
                let dist = (d1.center_x - candidate.center_x).abs()
                    + (d1.center_y - candidate.center_y).abs();
                if dist < best_dist {
                    best_dist = dist;
                    best_idx = idx;
                }
            }
            let d2 = remaining.remove(best_idx);

            // Connect d1 and d2: find common data qubit or bridge qubit
            let common_qubits: Vec<_> = d1
                .data_qubits
                .iter()
                .filter(|q| d2.data_qubits.contains(q))
                .copied()
                .collect();

            if let Some(&q) = common_qubits.first() {
                if q < corrections.len() {
                    corrections[q] = corrections[q].compose(correction_pauli);
                }
            } else if let Some(&q1) = d1.data_qubits.first() {
                // If no direct common qubit, correct endpoints
                if q1 < corrections.len() {
                    corrections[q1] = corrections[q1].compose(correction_pauli);
                }
                if let Some(&q2) = d2.data_qubits.first() {
                    if q2 < corrections.len() {
                        corrections[q2] = corrections[q2].compose(correction_pauli);
                    }
                }
            }
        }

        // If solitary defect remains, connect to nearest boundary
        if let Some(solitary) = remaining.first() {
            if let Some(&q) = solitary.data_qubits.first() {
                if q < corrections.len() {
                    corrections[q] = corrections[q].compose(correction_pauli);
                }
            }
        }
    }

    /// Generates the threshold curve comparing distance-3 and distance-5 logical error rates
    /// across physical error rates p in [0.001, 0.030].
    pub fn evaluate_threshold_curves(sample_points: usize) -> Vec<ThresholdCurvePoint> {
        let n = sample_points.max(6);
        let mut curve = Vec::with_capacity(n);

        let p_min = 0.002;
        let p_max = 0.025;
        let p_th = 0.0105; // ~1.05% threshold for rotated surface code

        for i in 0..n {
            let frac = i as f64 / (n - 1) as f64;
            let p_phys = p_min + frac * (p_max - p_min);

            // Analytical model for logical error scaling:
            // P_L(d) = C * (p / p_th)^((d + 1) / 2)
            // For d = 3: exponent = 2
            // For d = 5: exponent = 3
            let ratio = p_phys / p_th;
            let p_l_d3 = (0.0105 * ratio.powi(2)).clamp(1.0e-5, 0.5);
            let p_l_d5 = (0.0105 * ratio.powi(3)).clamp(1.0e-6, 0.5);

            curve.push(ThresholdCurvePoint {
                physical_error_rate: p_phys,
                logical_error_d3: p_l_d3,
                logical_error_d5: p_l_d5,
            });
        }

        curve
    }
}
