//! Multi-physics solver for non-equilibrium chiral phonon-driven superconductivity,
//! dynamic inversion symmetry breaking, and non-adiabatic Eliashberg pairing enhancement.

use phonon_core::constants::{BOLTZMANN_CONSTANT, MU_0};
use phonon_models::chiral_phonon_sc::{
    ChiralDriveMetrics, ChiralPhononDriveParams, TransientPairingMetrics, TransientPairingParams,
};

/// Multi-physics solver for non-equilibrium chiral phonon-driven superconductivity.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ChiralEliashbergSolver {
    pub drive_params: ChiralPhononDriveParams,
    pub pairing_params: TransientPairingParams,
}

impl ChiralEliashbergSolver {
    /// Creates a new chiral Eliashberg solver.
    pub fn new(
        drive_params: ChiralPhononDriveParams,
        pairing_params: TransientPairingParams,
    ) -> Self {
        Self {
            drive_params,
            pairing_params,
        }
    }

    /// Solves the chiral phonon drive metrics including orbital magnetic moment and inversion breaking.
    pub fn solve_chiral_drive(&self) -> ChiralDriveMetrics {
        self.drive_params.evaluate_drive_metrics()
    }

    /// Solves transient pairing enhancement metrics under optical drive.
    pub fn solve_transient_pairing(&self) -> TransientPairingMetrics {
        self.pairing_params.evaluate_pairing(&self.drive_params)
    }

    /// Solves transient critical temperature $T_c^{\\mathrm{transient}}$ in Kelvin ($\\text{K}$):
    /// $$T_c = \\frac{\\Delta_{\\mathrm{transient}}}{1.764 k_B}$$
    pub fn solve_transient_critical_temperature_k(&self) -> f64 {
        let metrics = self.solve_transient_pairing();
        let delta_j = metrics.transient_gap_mev * 1.602_176_634e-22;
        delta_j / (1.764 * BOLTZMANN_CONSTANT)
    }

    /// Solves temperature-dependent transient gap $\\Delta(T)$ in $\\text{meV}$:
    /// $$\Delta(T) = \Delta_{\mathrm{transient}} \tanh\left(1.74 \sqrt{\frac{T_c - T}{T}}\right)$$
    pub fn solve_transient_gap_at_temperature(&self, temperature_k: f64) -> f64 {
        let tc = self.solve_transient_critical_temperature_k();
        if temperature_k >= tc || temperature_k <= 0.0 {
            return 0.0;
        }
        let metrics = self.solve_transient_pairing();
        let reduced = ((tc - temperature_k) / temperature_k).max(0.0).sqrt();
        metrics.transient_gap_mev * (1.74 * reduced).tanh()
    }

    /// Solves local pair-density wave (PDW) spatial modulation $\\Delta(x) = \Delta_{\\mathrm{transient}} \cos(q_{\\mathrm{PDW}} x)$ in $\\text{meV}$.
    pub fn solve_pdw_spatial_profile(&self, x_nm: f64) -> f64 {
        let metrics = self.solve_transient_pairing();
        let x_m = x_nm * 1.0e-9;
        let phase = metrics.pdw_wavevector_inv_m * x_m;
        metrics.transient_gap_mev * phase.cos()
    }

    /// Solves effective pseudo-magnetic field $B_{\\mathrm{eff}}$ in Tesla generated by chiral phonon circulation:
    /// $$B_{\\mathrm{eff}} = \mu_0 \frac{\\mu_{\\mathrm{ph}} \mu_B}{V_{\\mathrm{unit}}}$$
    pub fn solve_effective_magnetic_field_tesla(&self, unit_cell_volume_nm3: f64) -> f64 {
        let metrics = self.solve_chiral_drive();
        let mu_b = 9.274_010_078e-24; // Bohr magneton (J/T)
        let vol_m3 = unit_cell_volume_nm3.max(0.01) * 1.0e-27;
        let dipole_moment_j_t = metrics.induced_magnetic_moment_bohr * mu_b;
        MU_0 * (dipole_moment_j_t / vol_m3)
    }
}
