[package]
name = "phonon-solver"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
phonon-core = { path = "../phonon-core" }
phonon-models = { path = "../phonon-models" }
thiserror = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
approx = { workspace = true }

[lints]
workspace = true
