//! Time-of-Flight (ToF) Pulsed LiDAR Point Cloud Synthesis Engine
//!
//! Simulates end-to-end LiDAR detection:
//! 1. Ray generation across 360-degree, MEMS, and Flash scanning architectures.
//! 2. BVH spatial intersection with multi-hit penetration for foliage/translucent objects.
//! 3. Two-way Beer-Lambert atmospheric attenuation and Kruse-Kim Mie scattering.
//! 4. Atmospheric volume backscatter clutter producing parasitic near-field false echoes.
//! 5. Photodetector noise equivalent power (NEP), SNR thresholding, and range jitter.

use crate::lidar::bvh::BvhTree;
use phonon_core::constants::SPEED_OF_LIGHT;
use phonon_models::em::ChannelRng;
use phonon_models::lidar::{AtmosphericCondition, LaserRay, LidarScannerConfig};
use rayon::prelude::*;

/// 3D LiDAR Point Cloud measurement point.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LidarPoint {
    /// World Cartesian X coordinate in meters.
    pub x: f64,
    /// World Cartesian Y coordinate in meters.
    pub y: f64,
    /// World Cartesian Z coordinate in meters.
    pub z: f64,
    /// Measured target range in meters.
    pub range_m: f64,
    /// Target calibrated intensity in [0.0, 255.0].
    pub intensity: f64,
    /// Peak received optical power in Watts.
    pub received_power_w: f64,
    /// Signal-to-Noise Ratio (SNR) in decibels.
    pub snr_db: f64,
    /// Laser channel / vertical ring index.
    pub channel_ring: u16,
    /// Azimuth angle in radians.
    pub azimuth_rad: f64,
    /// Elevation angle in radians.
    pub elevation_rad: f64,
    /// Echo order rank (0 for first echo, 1 for second, etc.).
    pub echo_index: u8,
    /// Flag indicating whether this is the final return in the pulse train.
    pub is_last_echo: bool,
    /// Flag indicating if this point was generated by atmospheric backscatter clutter (fog/smoke).
    pub is_backscatter_clutter: bool,
    /// Round-trip Time-of-Flight in nanoseconds.
    pub tof_ns: f64,
}

/// Point Cloud frame containing all synthesized points in a single scan cycle.
#[derive(Debug, Clone, PartialEq)]
pub struct LidarPointCloud {
    pub points: Vec<LidarPoint>,
    pub timestamp_s: f64,
    pub frame_index: usize,
}

impl LidarPointCloud {
    pub fn new(points: Vec<LidarPoint>, timestamp_s: f64, frame_index: usize) -> Self {
        Self {
            points,
            timestamp_s,
            frame_index,
        }
    }

    pub fn len(&self) -> usize {
        self.points.len()
    }

    pub fn is_empty(&self) -> bool {
        self.points.is_empty()
    }

    /// Filters points within distance range [min_m, max_m].
    pub fn filter_by_range(&self, min_m: f64, max_m: f64) -> Vec<LidarPoint> {
        self.points
            .iter()
            .copied()
            .filter(|p| p.range_m >= min_m && p.range_m <= max_m)
            .collect()
    }

    /// Filters out parasitic atmospheric backscatter clutter.
    pub fn filter_clutter(&self) -> Vec<LidarPoint> {
        self.points
            .iter()
            .copied()
            .filter(|p| !p.is_backscatter_clutter)
            .collect()
    }
}

/// Time-of-Flight LiDAR Simulation Engine.
#[derive(Debug, Clone, PartialEq)]
pub struct TofLidarEngine {
    pub scanner: LidarScannerConfig,
    pub atmosphere: AtmosphericCondition,
    pub bvh: BvhTree,
    pub min_snr_threshold_db: f64,
    pub multi_echo_enabled: bool,
    pub max_echoes_per_pulse: usize,
}

impl TofLidarEngine {
    /// Creates a new Time-of-Flight LiDAR engine.
    pub fn new(
        scanner: LidarScannerConfig,
        atmosphere: AtmosphericCondition,
        bvh: BvhTree,
    ) -> Self {
        Self {
            scanner,
            atmosphere,
            bvh,
            min_snr_threshold_db: 6.0, // Standard 6 dB minimum detection threshold
            multi_echo_enabled: true,
            max_echoes_per_pulse: 3,
        }
    }

    /// Configures multi-echo detection settings.
    pub fn with_multi_echo(mut self, enabled: bool, max_echoes: usize) -> Self {
        self.multi_echo_enabled = enabled;
        self.max_echoes_per_pulse = max_echoes.max(1);
        self
    }

    /// Configures minimum SNR threshold for echo discrimination.
    pub fn with_snr_threshold(mut self, min_snr_db: f64) -> Self {
        self.min_snr_threshold_db = min_snr_db;
        self
    }

    /// Simulates optical pulse propagation and echo detection for a single laser ray.
    pub fn scan_ray(
        &self,
        ch: usize,
        _sample: usize,
        ray: &LaserRay,
        rng: &mut ChannelRng,
    ) -> Vec<LidarPoint> {
        let max_range = self.scanner.max_range_m;
        let min_range = self.scanner.min_range_m;
        let alpha = self
            .atmosphere
            .extinction_coefficient_per_m(self.scanner.laser.wavelength_nm);

        let mut points = Vec::new();

        // Check for atmospheric volume backscatter clutter at close range under fog/smoke:
        let backscatter_range_test = 4.0; // 4 meters
        let p_backscatter = self
            .atmosphere
            .atmospheric_backscatter_power(&self.scanner.laser, backscatter_range_test);
        let bs_snr = p_backscatter / self.scanner.laser.noise_equivalent_power_w.max(1e-15);
        let bs_snr_db = if bs_snr > 1e-3 {
            10.0 * bs_snr.log10()
        } else {
            0.0
        };

        if bs_snr_db >= self.min_snr_threshold_db {
            let hit_p = ray.origin + ray.direction * backscatter_range_test;
            let (g, _) = rng.next_gaussian();
            let jitter_m = g * 0.05;
            let r_meas = (backscatter_range_test + jitter_m).max(min_range);
            let tof_ns = (2.0 * r_meas / SPEED_OF_LIGHT) * 1e9;

            points.push(LidarPoint {
                x: hit_p.x,
                y: hit_p.y,
                z: hit_p.z,
                range_m: r_meas,
                intensity: (bs_snr_db * 5.0).clamp(5.0, 255.0),
                received_power_w: p_backscatter,
                snr_db: bs_snr_db,
                channel_ring: ch as u16,
                azimuth_rad: ray.direction.y.atan2(ray.direction.x),
                elevation_rad: ray.direction.z.asin(),
                echo_index: 0,
                is_last_echo: false,
                is_backscatter_clutter: true,
                tof_ns,
            });
        }

        // Trace geometric surface hits through the BVH accelerator:
        let hits = if self.multi_echo_enabled {
            self.bvh.raycast_multi_hits(
                ray.origin,
                ray.direction,
                max_range,
                self.max_echoes_per_pulse,
            )
        } else if let Some(hit) = self.bvh.raycast(ray.origin, ray.direction, max_range) {
            vec![hit]
        } else {
            Vec::new()
        };

        let num_hits = hits.len();
        for (i, hit) in hits.into_iter().enumerate() {
            if hit.distance < min_range || hit.distance > max_range {
                continue;
            }

            // Incidence angle with surface normal:
            let cos_inc = hit.normal.dot(&(-ray.direction)).abs().clamp(0.0, 1.0);
            let inc_angle_rad = cos_inc.acos();

            // Returned optical power via LiDAR range equation:
            let p_rx = self.scanner.laser.returned_optical_power(
                hit.distance,
                hit.albedo,
                inc_angle_rad,
                alpha,
            );

            // Signal-to-Noise Ratio:
            let nep = self.scanner.laser.noise_equivalent_power_w.max(1e-15);
            let snr_linear = p_rx / nep;
            let snr_db = if snr_linear > 1e-3 {
                10.0 * snr_linear.log10()
            } else {
                0.0
            };

            // Threshold discriminator:
            if snr_db < self.min_snr_threshold_db {
                continue;
            }

            // Time of flight ranging jitter: sigma_R = (c * tau_p) / (2 * SNR):
            let tau_p = self.scanner.laser.pulse_duration_s;
            let sigma_r = (SPEED_OF_LIGHT * tau_p) / (2.0 * snr_linear.max(1.0));
            // Clamp jitter to realistic physical bounds (e.g. 1 mm to 5 cm):
            let sigma_r_clamped = sigma_r.clamp(0.001, 0.05);

            let (g, _) = rng.next_gaussian();
            let r_noisy = (hit.distance + g * sigma_r_clamped).max(min_range);
            let tof_ns = (2.0 * r_noisy / SPEED_OF_LIGHT) * 1e9;

            let hit_p_noisy = ray.origin + ray.direction * r_noisy;
            let intensity = ((p_rx / 1e-6).log10() * 30.0 + 100.0).clamp(0.0, 255.0);

            let is_last = i == num_hits - 1;
            let echo_idx = (points.len()).min(255) as u8;

            points.push(LidarPoint {
                x: hit_p_noisy.x,
                y: hit_p_noisy.y,
                z: hit_p_noisy.z,
                range_m: r_noisy,
                intensity,
                received_power_w: p_rx,
                snr_db,
                channel_ring: ch as u16,
                azimuth_rad: ray.direction.y.atan2(ray.direction.x),
                elevation_rad: ray.direction.z.asin(),
                echo_index: echo_idx,
                is_last_echo: is_last,
                is_backscatter_clutter: false,
                tof_ns,
            });
        }

        points
    }

    /// Renders a complete point cloud frame across all scanning rays in parallel using Rayon.
    pub fn scan_point_cloud(&self, frame_index: usize, seed: u64) -> LidarPointCloud {
        let rays = self.scanner.generate_scan_rays();

        let nested_points: Vec<Vec<LidarPoint>> = rays
            .into_par_iter()
            .enumerate()
            .map(|(ray_idx, (ch, sample, ray))| {
                let ray_seed = seed
                    .wrapping_add((ray_idx as u64) << 16)
                    .wrapping_add(ch as u64);
                let mut rng = ChannelRng::new(ray_seed);
                self.scan_ray(ch, sample, &ray, &mut rng)
            })
            .collect();

        let total_count: usize = nested_points.iter().map(|v| v.len()).sum();
        let mut flat_points = Vec::with_capacity(total_count);
        for list in nested_points {
            flat_points.extend(list);
        }

        let timestamp_s = frame_index as f64 * 0.1; // 10 Hz nominal
        LidarPointCloud::new(flat_points, timestamp_s, frame_index)
    }
}
