//! Kinetic particle states, relativistic kinematics, magnetic moments,
//! pitch angle scattering, and trapped banana orbit classification.

use super::constants::{
    ALPHA_MASS, DEUTERON_MASS, ELECTRON_MASS, ELEMENTARY_CHARGE, EV_TO_JOULES, PROTON_MASS,
    SPEED_OF_LIGHT, TRITON_MASS,
};

/// Charged plasma particle species.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PlasmaSpecies {
    /// Electron ($e^-$).
    Electron,
    /// Proton / Hydrogen nucleus ($H^+$).
    Proton,
    /// Deuterium nucleus ($D^+$).
    Deuteron,
    /// Tritium nucleus ($T^+$).
    Triton,
    /// Alpha particle ($^4\text{He}^{2+}$) generated by D-T fusion.
    AlphaParticle,
}

impl PlasmaSpecies {
    /// Rest mass in kilograms (kg).
    pub fn mass(&self) -> f64 {
        match self {
            Self::Electron => ELECTRON_MASS,
            Self::Proton => PROTON_MASS,
            Self::Deuteron => DEUTERON_MASS,
            Self::Triton => TRITON_MASS,
            Self::AlphaParticle => ALPHA_MASS,
        }
    }

    /// Electric charge in Coulombs (C).
    pub fn charge(&self) -> f64 {
        match self {
            Self::Electron => -ELEMENTARY_CHARGE,
            Self::Proton | Self::Deuteron | Self::Triton => ELEMENTARY_CHARGE,
            Self::AlphaParticle => 2.0 * ELEMENTARY_CHARGE,
        }
    }

    /// Charge number $Z$.
    pub fn charge_number(&self) -> f64 {
        match self {
            Self::Electron => -1.0,
            Self::Proton | Self::Deuteron | Self::Triton => 1.0,
            Self::AlphaParticle => 2.0,
        }
    }
}

/// Kinetic state of an individual charged particle in phase space $(\mathbf{x}, \mathbf{v})$.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct KineticParticle {
    /// Particle species.
    pub species: PlasmaSpecies,
    /// Position vector $[x, y, z]$ in Cartesian coordinates (meters).
    pub position: [f64; 3],
    /// Velocity vector $[v_x, v_y, v_z]$ in Cartesian coordinates (m/s).
    pub velocity: [f64; 3],
}

impl KineticParticle {
    /// Creates a new kinetic particle state.
    pub fn new(species: PlasmaSpecies, position: [f64; 3], velocity: [f64; 3]) -> Self {
        Self {
            species,
            position,
            velocity,
        }
    }

    /// Particle speed $v = \|\mathbf{v}\|$ (m/s).
    pub fn speed(&self) -> f64 {
        (self.velocity[0].powi(2) + self.velocity[1].powi(2) + self.velocity[2].powi(2)).sqrt()
    }

    /// Kinetic energy in Joules (J).
    pub fn kinetic_energy_joules(&self) -> f64 {
        0.5 * self.species.mass() * self.speed().powi(2)
    }

    /// Kinetic energy in electron-volts (eV).
    pub fn kinetic_energy_ev(&self) -> f64 {
        self.kinetic_energy_joules() / EV_TO_JOULES
    }

    /// Kinetic energy in kilo-electron-volts (keV).
    pub fn kinetic_energy_kev(&self) -> f64 {
        self.kinetic_energy_ev() / 1000.0
    }

    /// Relativistic Lorentz factor $\gamma = 1 / \sqrt{1 - v^2/c^2}$.
    pub fn lorentz_factor(&self) -> f64 {
        let beta = (self.speed() / SPEED_OF_LIGHT).clamp(0.0, 0.999_999);
        1.0 / (1.0 - beta.powi(2)).sqrt()
    }

    /// Cylindrical coordinates $(R, \phi, Z)$ where $R = \sqrt{x^2 + y^2}$.
    pub fn cylindrical_position(&self) -> (f64, f64, f64) {
        let r = (self.position[0].powi(2) + self.position[1].powi(2)).sqrt();
        let phi = self.position[1].atan2(self.position[0]);
        let z = self.position[2];
        (r, phi, z)
    }

    /// Parallel velocity component $v_\parallel = \mathbf{v} \cdot \hat{\mathbf{b}}$ along local unit $\hat{\mathbf{b}}$.
    pub fn v_parallel(&self, b_unit: [f64; 3]) -> f64 {
        self.velocity[0] * b_unit[0] + self.velocity[1] * b_unit[1] + self.velocity[2] * b_unit[2]
    }

    /// Perpendicular velocity component $v_\perp = \sqrt{v^2 - v_\parallel^2}$.
    pub fn v_perp(&self, b_unit: [f64; 3]) -> f64 {
        let v_par = self.v_parallel(b_unit);
        let v_sq = self.speed().powi(2);
        (v_sq - v_par.powi(2)).max(0.0).sqrt()
    }

    /// Pitch angle $\theta = \arccos(v_\parallel / v)$ in radians.
    pub fn pitch_angle(&self, b_unit: [f64; 3]) -> f64 {
        let v = self.speed();
        if v < 1e-9 {
            0.0
        } else {
            let cosine = (self.v_parallel(b_unit) / v).clamp(-1.0, 1.0);
            cosine.acos()
        }
    }

    /// First adiabatic invariant / magnetic moment $\mu = \frac{m v_\perp^2}{2 B}$ in $J/T$.
    pub fn magnetic_moment(&self, b_magnitude: f64, b_unit: [f64; 3]) -> f64 {
        let v_perp = self.v_perp(b_unit);
        let m = self.species.mass();
        (m * v_perp.powi(2)) / (2.0 * b_magnitude.max(1e-6))
    }

    /// Gyroradius / Larmor radius $\rho_L = \frac{m v_\perp}{|q| B}$ in meters.
    pub fn larmor_radius(&self, b_magnitude: f64, b_unit: [f64; 3]) -> f64 {
        let v_perp = self.v_perp(b_unit);
        let m = self.species.mass();
        let q = self.species.charge().abs();
        (m * v_perp) / (q * b_magnitude.max(1e-6))
    }

    /// Classifies whether particle is trapped in magnetic well (banana orbit) vs passing circulating.
    ///
    /// In a tokamak with inverse aspect ratio $\epsilon = r / R_0$, trapping occurs when:
    /// $$\sin^2\theta > \frac{B_{min}}{B_{max}} \approx \frac{1 - \epsilon}{1 + \epsilon}$$
    pub fn is_trapped(&self, epsilon: f64, b_unit: [f64; 3]) -> bool {
        let theta = self.pitch_angle(b_unit);
        let sin2 = theta.sin().powi(2);
        let eps = epsilon.clamp(0.0, 0.99);
        let threshold = (1.0 - eps) / (1.0 + eps);
        sin2 > threshold
    }

    /// Banana bounce frequency $\omega_b \approx \frac{v}{R_0 q} \sqrt{\frac{\epsilon}{2}}$ in radians/sec.
    pub fn bounce_frequency(&self, q_safety: f64, r0: f64, epsilon: f64) -> f64 {
        let v = self.speed();
        let safe_q = q_safety.max(0.1);
        let safe_r0 = r0.max(0.1);
        let safe_eps = epsilon.clamp(0.0, 1.0);
        (v / (safe_r0 * safe_q)) * (0.5 * safe_eps).sqrt()
    }

    /// Radial banana orbit width $\Delta r_b \approx \frac{q}{\sqrt{\epsilon}} \rho_L$ in meters.
    pub fn banana_width(&self, q_safety: f64, epsilon: f64, b_mag: f64, b_unit: [f64; 3]) -> f64 {
        let rho_l = self.larmor_radius(b_mag, b_unit);
        let safe_q = q_safety.max(0.1);
        let safe_eps = epsilon.clamp(1e-4, 1.0);
        (safe_q / safe_eps.sqrt()) * rho_l
    }
}
