//! Integration tests for Atomistic Density Functional Theory (DFT) Wannier functions,
//! real-space hopping interpolation, bandstructure dispersion, and Density of States (DOS).

use phonon_models::{Complex, WannierHamiltonian};

#[test]
fn test_wannier90_hr_dat_parsing_and_dispersion() {
    // Generate synthetic Wannier90 hr.dat for a 1D chain / 2-band system
    // 2 Wannier functions (s-p hybridized), nearest-neighbor hoppings
    let hr_content = "Generated by Phonon DFT interface test
2
3
1 1 1
0 0 0 1 1 -1.5 0.0
0 0 0 2 2  1.5 0.0
0 0 0 1 2  0.2 0.0
0 0 0 2 1  0.2 0.0
1 0 0 1 1 -0.8 0.0
1 0 0 2 2  0.8 0.0
1 0 0 1 2  0.1 0.0
1 0 0 2 1  0.1 0.0
-1 0 0 1 1 -0.8 0.0
-1 0 0 2 2  0.8 0.0
-1 0 0 1 2  0.1 0.0
-1 0 0 2 1  0.1 0.0
";

    let lattice = [[3.0, 0.0, 0.0], [0.0, 3.0, 0.0], [0.0, 0.0, 3.0]];
    let wannier = WannierHamiltonian::from_hr_text(hr_content, lattice)
        .expect("Should parse synthetic Wannier90 _hr.dat successfully");

    assert_eq!(wannier.num_orbitals, 2);
    assert_eq!(wannier.hoppings.len(), 12);

    // Evaluate H(k) at Gamma (k = 0)
    let k_gamma = [0.0, 0.0, 0.0];
    let bands_gamma = wannier.eigenvalues_at_k(&k_gamma);
    assert_eq!(bands_gamma.len(), 2);
    // At Gamma, hoppings add constructively:
    // Band 1: -1.5 + 2 * (-0.8) = -3.1 eV
    // Band 2: +1.5 + 2 * (0.8) = +3.1 eV
    assert!(
        bands_gamma[0] < bands_gamma[1],
        "Bands must be sorted ascending: {:?}",
        bands_gamma
    );
    assert!(
        (bands_gamma[0] - (-3.1)).abs() < 0.05,
        "Band 1 at Gamma should be approx -3.1 eV, got {}",
        bands_gamma[0]
    );
    assert!(
        (bands_gamma[1] - 3.1).abs() < 0.05,
        "Band 2 at Gamma should be approx +3.1 eV, got {}",
        bands_gamma[1]
    );

    // Evaluate at Brillouin zone edge X (kx * a = pi)
    let k_x = [
        std::f64::consts::PI / wannier.lattice_vectors[0][0],
        0.0,
        0.0,
    ];
    let bands_x = wannier.eigenvalues_at_k(&k_x);
    // At zone boundary, hoppings cancel out: -1.5 - 2*(-0.8) = +0.1 eV
    assert!(
        bands_x[0] > bands_gamma[0],
        "Dispersion must have band minimum at Gamma"
    );
    assert!(
        bands_x[1] < bands_gamma[1],
        "Upper band must have maximum at Gamma"
    );
}

#[test]
fn test_hermitian_jacobi_eigensolver_and_dos() {
    // 3x3 Wannier model representing t2g orbitals (dxy, dyz, dxz)
    let lattice = [[3.0, 0.0, 0.0], [0.0, 3.0, 0.0], [0.0, 0.0, 3.0]];
    let mut wannier = WannierHamiltonian::new(3, lattice);

    wannier.add_hopping([0, 0, 0], 0, 0, Complex::new(0.0, 0.0));
    wannier.add_hopping([0, 0, 0], 1, 1, Complex::new(0.5, 0.0));
    wannier.add_hopping([0, 0, 0], 2, 2, Complex::new(1.0, 0.0));
    // Off-diagonal Hermitian coupling between orbital 0 and 1
    wannier.add_hopping([0, 0, 0], 0, 1, Complex::new(0.2, 0.1));
    wannier.add_hopping([0, 0, 0], 1, 0, Complex::new(0.2, -0.1));

    // Compute DOS along a k-mesh
    let k_points = vec![
        [0.0, 0.0, 0.0],
        [0.1, 0.0, 0.0],
        [0.2, 0.0, 0.0],
        [0.3, 0.0, 0.0],
        [0.5, 0.0, 0.0],
    ];

    let sigma_ev = 0.1;
    let energies = [-0.5, 0.0, 0.5, 1.0, 1.5];
    let dos = wannier.density_of_states(&k_points, &energies, sigma_ev);

    assert_eq!(dos.len(), energies.len());
    // DOS must be non-negative everywhere
    for &d in &dos {
        assert!(d >= 0.0, "DOS must be strictly non-negative: {}", d);
    }

    // Peak of DOS should be near the orbital energies (0.0 to 1.0 eV)
    let dos_at_0_5 = dos[2];
    let dos_at_far = dos[0];
    assert!(
        dos_at_0_5 > dos_at_far * 2.0,
        "DOS must peak near eigenvalues: {} vs {}",
        dos_at_0_5,
        dos_at_far
    );

    // Fermi energy bisection: for 2 valence electrons in 3 bands, E_F should be around ~0.5 eV
    let e_fermi = wannier.fermi_energy(&k_points, 2.0, 300.0);
    assert!(
        e_fermi > -0.2 && e_fermi < 1.2,
        "Fermi energy must reside between lower and upper bands, got {}",
        e_fermi
    );
}
