use phonon_models::valleytronics::{BerryCurvatureDipole, TmdMaterialParams, ValleyLattice};
use phonon_solver::valleytronics::{
    SemiclassicalValleyBoltzmannSolver, ValleyHallTransistorSolver,
};

#[test]
fn test_berry_curvature_dipole_symmetry() {
    // Untilted TMD preserves C3v symmetry: Berry dipole should vanish
    let untilted = TmdMaterialParams::wse2_monolayer();
    let lattice_untilted = ValleyLattice::new(untilted);
    let mut dipole_untilted = BerryCurvatureDipole::new(lattice_untilted);
    let d_zero = dipole_untilted.compute_dipole(0.65, 16);

    assert!(
        d_zero.abs() < 1e-12,
        "Berry dipole must vanish in untilted C3v lattice: got {}",
        d_zero
    );

    // Strained/tilted TMD breaks in-plane mirror symmetry: non-zero Berry dipole
    let tilted = TmdMaterialParams::strained_tilted_tmd(1.5e5);
    let lattice_tilted = ValleyLattice::new(tilted);
    let mut dipole_tilted = BerryCurvatureDipole::new(lattice_tilted);
    let d_nonzero = dipole_tilted.compute_dipole(0.65, 16);

    assert!(
        d_nonzero.abs() > 1e-15,
        "Tilted TMD must possess non-zero Berry curvature dipole: got {}",
        d_nonzero
    );
}

#[test]
fn test_nonlinear_hall_current_and_rectification() {
    let params = TmdMaterialParams::strained_tilted_tmd(1.0e5);
    let mut solver = SemiclassicalValleyBoltzmannSolver::new(params);

    let res = solver.solve(5.0e4, 0.65, 16);

    // Non-linear Hall current must be generated
    assert!(
        res.nonlinear_hall_current_a_m > 0.0,
        "Transverse non-linear Hall current must be non-zero"
    );

    // Rectification ratio must exceed 20 dB
    assert!(
        res.rectification_ratio_db >= 20.0,
        "Non-linear Hall rectification ratio must be >= 20 dB: got {}",
        res.rectification_ratio_db
    );

    // Pure valley current must be non-zero
    assert!(
        res.pure_valley_current_a_m > 0.0,
        "Pure valley current must be generated by anomalous velocity"
    );
}

#[test]
fn test_valley_hall_transistor_switching() {
    let params = TmdMaterialParams::strained_tilted_tmd(1.2e5);
    let mut trans_solver = ValleyHallTransistorSolver::new(params);

    let result = trans_solver.solve(4.0e4);

    assert!(
        result.on_off_ratio_db >= 20.0,
        "Transistor ON/OFF switching ratio must exceed 20 dB: got {}",
        result.on_off_ratio_db
    );

    assert!(
        result.on_rectification_db >= 20.0,
        "ON-state rectification must exceed 20 dB: got {}",
        result.on_rectification_db
    );
}
