[package]
name = "phonon-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true, optional = true }

[features]
default = []
serde = ["dep:serde"]

[dev-dependencies]
egui = { workspace = true }
phonon-models = { path = "../phonon-models" }
phonon-solver = { path = "../phonon-solver" }
phonon-thermal = { path = "../phonon-thermal" }
phonon-gui = { path = "../phonon-gui" }

[lints]
workspace = true
