//! Chiral-Induced Spin Selectivity (CISS) & Helical Quantum Transport Models.
//!
//! Formulates tight-binding Hamiltonians with microscopic spin-orbit coupling (SOC)
//! across 3D helical oligomers and DNA-like polymers:
//! 1. Helical geometry: radius $R$, pitch $P$, twist angle $\Delta\phi$, and chirality $\chi \in \{+1, -1, 0\}$.
//! 2. Microscopic SOC generated by radial chiral electrostatic fields $\mathbf{E}_n \propto \hat{\mathbf{r}}_n$
//!    crossed with bond vector $\mathbf{d}_n = \mathbf{r}_{n+1} - \mathbf{r}_n$:
//!    \[\boldsymbol{\Omega}_n = \hat{\mathbf{r}}_n \times \mathbf{d}_n\]
//! 3. Spin-dependent hopping:
//!    \[t_{n, n+1} = -t_0 \mathbf{I}_{2\times 2} - i \lambda_{SO} (\boldsymbol{\sigma} \cdot \hat{\boldsymbol{\Omega}}_n)\]
//! 4. Non-Equilibrium Green's Function (NEGF) / Landauer-Büttiker spin-resolved transmission:
//!    \[P_s(E) = \frac{T_\uparrow(E) - T_\downarrow(E)}{T_\uparrow(E) + T_\downarrow(E)} > 60\%\]
//!    demonstrating room-temperature spin selectivity in non-magnetic chiral molecules.

use crate::quantum::Complex;
use crate::spintronics::Vec3;
use phonon_core::{BOLTZMANN_CONSTANT, ELEMENTARY_CHARGE, PLANCK_CONSTANT};

/// Chirality handedness of the molecular helix.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Chirality {
    /// Right-handed helix ($\chi = +1.0$).
    RightHanded,
    /// Left-handed helix ($\chi = -1.0$).
    LeftHanded,
    /// Achiral linear structure ($\chi = 0.0$).
    Achiral,
}

impl Chirality {
    #[inline(always)]
    pub fn sign(self) -> f64 {
        match self {
            Self::RightHanded => 1.0,
            Self::LeftHanded => -1.0,
            Self::Achiral => 0.0,
        }
    }
}

/// 3D Geometry of a chiral molecular helix (e.g. DNA, peptide alpha-helix, or helical oligomer).
#[derive(Debug, Clone, PartialEq)]
pub struct ChiralHelixGeometry {
    /// Helix radius $R$ in nanometers ($nm$).
    pub radius_nm: f64,
    /// Helix pitch $P$ in nanometers ($nm$) (axial length per full $2\pi$ revolution).
    pub pitch_nm: f64,
    /// Twist angle per site $\Delta\phi$ in radians.
    pub twist_angle_rad: f64,
    /// Number of molecular monomer / nucleotide sites $N$.
    pub num_sites: usize,
    /// Chirality handedness.
    pub chirality: Chirality,
}

impl ChiralHelixGeometry {
    pub fn new(
        radius_nm: f64,
        pitch_nm: f64,
        twist_angle_rad: f64,
        num_sites: usize,
        chirality: Chirality,
    ) -> Self {
        assert!(num_sites >= 2, "Helical chain must have at least 2 sites");
        Self {
            radius_nm,
            pitch_nm,
            twist_angle_rad,
            num_sites,
            chirality,
        }
    }

    /// Axial distance per site step $\Delta z$ in nanometers.
    #[inline(always)]
    pub fn delta_z_nm(&self) -> f64 {
        let full_turn_rad = 2.0 * std::f64::consts::PI;
        self.pitch_nm * (self.twist_angle_rad.abs() / full_turn_rad)
    }

    /// 3D Cartesian coordinates $\mathbf{r}_n$ of site $n \in [0, N-1]$.
    pub fn site_position(&self, n: usize) -> Vec3 {
        let dz = self.delta_z_nm();
        let z = (n as f64) * dz;
        match self.chirality {
            Chirality::Achiral => Vec3::new(0.0, 0.0, z),
            _ => {
                let phi = (n as f64) * self.twist_angle_rad;
                let chi = self.chirality.sign();
                let x = self.radius_nm * phi.cos();
                let y = chi * self.radius_nm * phi.sin();
                Vec3::new(x, y, z)
            }
        }
    }

    /// Unit radial vector $\hat{\mathbf{r}}_n$ directed outward from helical cylinder axis.
    pub fn radial_unit_vector(&self, n: usize) -> Vec3 {
        match self.chirality {
            Chirality::Achiral => Vec3::new(1.0, 0.0, 0.0),
            _ => {
                let phi = (n as f64) * self.twist_angle_rad;
                let chi = self.chirality.sign();
                Vec3::new(phi.cos(), chi * phi.sin(), 0.0)
            }
        }
    }

    /// Bond displacement vector $\mathbf{d}_n = \mathbf{r}_{n+1} - \mathbf{r}_n$.
    pub fn bond_vector(&self, n: usize) -> Vec3 {
        assert!(
            n + 1 < self.num_sites,
            "Site index out of bounds for bond vector"
        );
        let r1 = self.site_position(n);
        let r2 = self.site_position(n + 1);
        Vec3::new(r2.x - r1.x, r2.y - r1.y, r2.z - r1.z)
    }

    /// Spin-orbit cross product vector:
    /// \[\boldsymbol{\Omega}_n = \hat{\mathbf{r}}_n \times \mathbf{d}_n\]
    pub fn spin_orbit_vector(&self, n: usize) -> Vec3 {
        let r_hat = self.radial_unit_vector(n);
        let d = self.bond_vector(n);
        r_hat.cross(d)
    }

    /// Normalized spin-orbit unit vector $\hat{\boldsymbol{\Omega}}_n$.
    pub fn spin_orbit_unit_vector(&self, n: usize) -> Vec3 {
        let omega = self.spin_orbit_vector(n);
        let norm = (omega.x * omega.x + omega.y * omega.y + omega.z * omega.z).sqrt();
        if norm > 1e-15 {
            Vec3::new(omega.x / norm, omega.y / norm, omega.z / norm)
        } else {
            Vec3::ZERO
        }
    }
}

/// Dense square complex matrix for pure safe-Rust quantum linear algebra.
#[derive(Debug, Clone, PartialEq)]
pub struct ComplexMatrix {
    pub dim: usize,
    pub data: Vec<Complex>,
}

impl ComplexMatrix {
    pub fn zeros(dim: usize) -> Self {
        Self {
            dim,
            data: vec![Complex::ZERO; dim * dim],
        }
    }

    pub fn identity(dim: usize) -> Self {
        let mut m = Self::zeros(dim);
        for i in 0..dim {
            m.set(i, i, Complex::ONE);
        }
        m
    }

    #[inline(always)]
    pub fn get(&self, r: usize, c: usize) -> Complex {
        self.data[r * self.dim + c]
    }

    #[inline(always)]
    pub fn set(&mut self, r: usize, c: usize, val: Complex) {
        self.data[r * self.dim + c] = val;
    }

    #[inline(always)]
    pub fn add_at(&mut self, r: usize, c: usize, val: Complex) {
        let idx = r * self.dim + c;
        self.data[idx] = self.data[idx] + val;
    }

    pub fn dagger(&self) -> Self {
        let mut adj = Self::zeros(self.dim);
        for r in 0..self.dim {
            for c in 0..self.dim {
                adj.set(c, r, self.get(r, c).conj());
            }
        }
        adj
    }

    pub fn trace(&self) -> Complex {
        let mut tr = Complex::ZERO;
        for i in 0..self.dim {
            tr = tr + self.get(i, i);
        }
        tr
    }

    pub fn hermitian_symmetrize(&mut self) {
        for r in 0..self.dim {
            let diag = self.get(r, r);
            self.set(r, r, Complex::new(diag.re, 0.0));
            for c in (r + 1)..self.dim {
                let a = self.get(r, c);
                let b = self.get(c, r).conj();
                let avg = (a + b) * 0.5;
                self.set(r, c, avg);
                self.set(c, r, avg.conj());
            }
        }
    }

    pub fn add(&self, other: &Self) -> Self {
        assert_eq!(self.dim, other.dim);
        let mut res = Self::zeros(self.dim);
        for i in 0..(self.dim * self.dim) {
            res.data[i] = self.data[i] + other.data[i];
        }
        res
    }

    pub fn sub(&self, other: &Self) -> Self {
        assert_eq!(self.dim, other.dim);
        let mut res = Self::zeros(self.dim);
        for i in 0..(self.dim * self.dim) {
            res.data[i] = self.data[i] - other.data[i];
        }
        res
    }

    pub fn mul(&self, other: &Self) -> Self {
        assert_eq!(self.dim, other.dim);
        let n = self.dim;
        let mut res = Self::zeros(n);
        for i in 0..n {
            for k in 0..n {
                let a_ik = self.get(i, k);
                if a_ik.norm_sq() < 1e-30 {
                    continue;
                }
                for j in 0..n {
                    let term = a_ik * other.get(k, j);
                    res.add_at(i, j, term);
                }
            }
        }
        res
    }

    pub fn scale(&self, s: Complex) -> Self {
        let mut res = Self::zeros(self.dim);
        for i in 0..(self.dim * self.dim) {
            res.data[i] = self.data[i] * s;
        }
        res
    }

    pub fn scale_real(&self, s: f64) -> Self {
        let mut res = Self::zeros(self.dim);
        for i in 0..(self.dim * self.dim) {
            res.data[i] = self.data[i] * s;
        }
        res
    }

    /// Computes the matrix inverse $A^{-1}$ using Gauss-Jordan elimination with partial pivoting.
    pub fn invert(&self) -> Option<Self> {
        let n = self.dim;
        let mut a = self.clone();
        let mut inv = Self::identity(n);

        for col in 0..n {
            // Find pivot with maximum magnitude in current column
            let mut max_pivot = a.get(col, col).norm_sq();
            let mut pivot_row = col;
            for row in (col + 1)..n {
                let mag = a.get(row, col).norm_sq();
                if mag > max_pivot {
                    max_pivot = mag;
                    pivot_row = row;
                }
            }

            if max_pivot < 1e-30 {
                return None; // Singular matrix
            }

            // Swap rows
            if pivot_row != col {
                for k in 0..n {
                    let tmp_a = a.get(col, k);
                    a.set(col, k, a.get(pivot_row, k));
                    a.set(pivot_row, k, tmp_a);

                    let tmp_inv = inv.get(col, k);
                    inv.set(col, k, inv.get(pivot_row, k));
                    inv.set(pivot_row, k, tmp_inv);
                }
            }

            // Scale pivot row to 1
            let pivot_val = a.get(col, col);
            for k in 0..n {
                a.set(col, k, a.get(col, k) / pivot_val);
                inv.set(col, k, inv.get(col, k) / pivot_val);
            }

            // Eliminate column in other rows
            for row in 0..n {
                if row == col {
                    continue;
                }
                let factor = a.get(row, col);
                if factor.norm_sq() > 1e-30 {
                    for k in 0..n {
                        let new_a = a.get(row, k) - factor * a.get(col, k);
                        a.set(row, k, new_a);

                        let new_inv = inv.get(row, k) - factor * inv.get(col, k);
                        inv.set(row, k, new_inv);
                    }
                }
            }
        }

        Some(inv)
    }

    /// Eigensystem for complex Hermitian matrices ($A = A^\dagger$) using Jacobi rotation.
    /// Returns sorted eigenvalues in ascending order and corresponding eigenvectors as columns of $V$.
    pub fn eigensystem_hermitian(&self, max_sweeps: usize, tolerance: f64) -> (Vec<f64>, Self) {
        let n = self.dim;
        let mut a = self.clone();
        a.hermitian_symmetrize();
        let mut v = Self::identity(n);

        for _ in 0..max_sweeps {
            // Find off-diagonal entry with maximum squared magnitude
            let mut max_off = 0.0;
            let mut p = 0;
            let mut q = 1;

            for i in 0..n {
                for j in (i + 1)..n {
                    let mag = a.get(i, j).norm_sq();
                    if mag > max_off {
                        max_off = mag;
                        p = i;
                        q = j;
                    }
                }
            }

            if max_off.sqrt() < tolerance {
                break;
            }

            // 2x2 Hermitian submatrix diagonalization
            let a_pp = a.get(p, p).re;
            let a_qq = a.get(q, q).re;
            let a_pq = a.get(p, q);

            let r = a_pq.abs();
            if r < 1e-30 {
                continue;
            }
            let phase = a_pq / Complex::new(r, 0.0);

            let tau = (a_qq - a_pp) / (2.0 * r);
            let t = if tau >= 0.0 {
                1.0 / (tau + (1.0 + tau * tau).sqrt())
            } else {
                -1.0 / (-tau + (1.0 + tau * tau).sqrt())
            };

            let c = 1.0 / (1.0 + t * t).sqrt();
            let s = t * c;

            // Apply Jacobi unitary rotation
            for k in 0..n {
                if k != p && k != q {
                    let a_kp = a.get(k, p);
                    let a_kq = a.get(k, q);

                    let new_kp = a_kp * c - (a_kq * phase.conj()) * s;
                    let new_kq = (a_kp * phase) * s + a_kq * c;

                    a.set(k, p, new_kp);
                    a.set(p, k, new_kp.conj());
                    a.set(k, q, new_kq);
                    a.set(q, k, new_kq.conj());
                }

                // Update eigenvector accumulator V
                let v_kp = v.get(k, p);
                let v_kq = v.get(k, q);

                let new_vkp = v_kp * c - (v_kq * phase.conj()) * s;
                let new_vkq = (v_kp * phase) * s + v_kq * c;

                v.set(k, p, new_vkp);
                v.set(k, q, new_vkq);
            }

            a.set(p, p, Complex::new(a_pp - t * r, 0.0));
            a.set(q, q, Complex::new(a_qq + t * r, 0.0));
            a.set(p, q, Complex::ZERO);
            a.set(q, p, Complex::ZERO);
        }

        // Extract eigenvalues and sort ascending
        let mut ev_indices: Vec<(f64, usize)> = (0..n).map(|i| (a.get(i, i).re, i)).collect();
        ev_indices.sort_by(|x, y| x.0.partial_cmp(&y.0).unwrap_or(std::cmp::Ordering::Equal));

        let eigenvalues: Vec<f64> = ev_indices.iter().map(|&(ev, _)| ev).collect();
        let mut sorted_v = Self::zeros(n);
        for (new_col, &(_, old_col)) in ev_indices.iter().enumerate() {
            for row in 0..n {
                sorted_v.set(row, new_col, v.get(row, old_col));
            }
        }

        (eigenvalues, sorted_v)
    }

    /// Convenience method to compute only eigenvalues of a complex Hermitian matrix.
    pub fn eigenvalues_hermitian(&self) -> Vec<f64> {
        let (evals, _) = self.eigensystem_hermitian(100, 1e-12);
        evals
    }
}

/// Spin-resolved quantum transmission result from NEGF / Landauer-Büttiker solver.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CissTransmission {
    pub energy_ev: f64,
    pub t_up: f64,
    pub t_down: f64,
    pub t_total: f64,
    pub spin_polarization: f64,
}

/// Multi-orbital / tight-binding Hamiltonian model on a 3D helical chain
/// with microscopic spin-orbit coupling modeling the Chiral-Induced Spin Selectivity (CISS) effect.
#[derive(Debug, Clone, PartialEq)]
pub struct CissHamiltonian {
    /// 3D Geometry of the chiral helix.
    pub geometry: ChiralHelixGeometry,
    /// On-site electrostatic potential energy $\epsilon_0$ in electron-volts ($eV$).
    pub on_site_energy_ev: f64,
    /// Spin-conserving nearest-neighbor hopping integral $t_0$ in electron-volts ($eV$).
    pub hopping_energy_ev: f64,
    /// Microscopic spin-orbit coupling parameter $\lambda_{SO}$ in electron-volts ($eV$).
    pub spin_orbit_coupling_ev: f64,
    /// Contact lead coupling self-energy broadening $\Gamma_0$ in electron-volts ($eV$).
    pub contact_coupling_ev: f64,
    /// Inelastic phonon-assisted dephasing broadening $\Gamma_{deph}$ in electron-volts ($eV$).
    pub dephasing_rate_ev: f64,
    /// Chiral backbone electrostatic field strength $V_{chiral}$ in electron-volts ($eV$).
    pub chiral_potential_ev: f64,
}

impl CissHamiltonian {
    pub fn new(
        geometry: ChiralHelixGeometry,
        on_site_energy_ev: f64,
        hopping_energy_ev: f64,
        spin_orbit_coupling_ev: f64,
        contact_coupling_ev: f64,
    ) -> Self {
        Self {
            geometry,
            on_site_energy_ev,
            hopping_energy_ev,
            spin_orbit_coupling_ev,
            contact_coupling_ev,
            dephasing_rate_ev: 0.02,
            chiral_potential_ev: 0.15,
        }
    }

    pub fn with_dephasing(mut self, dephasing_ev: f64) -> Self {
        self.dephasing_rate_ev = dephasing_ev;
        self
    }

    pub fn with_chiral_potential(mut self, potential_ev: f64) -> Self {
        self.chiral_potential_ev = potential_ev;
        self
    }

    /// Assembles the $(2N) \times (2N)$ Hermitian tight-binding Hamiltonian in spin-orbit space:
    /// State basis: $|n, \sigma\rangle$ where $n \in [0, N-1]$ and $\sigma \in \{0 (\uparrow), 1 (\downarrow)\}$.
    pub fn build_hamiltonian_matrix(&self) -> ComplexMatrix {
        let n = self.geometry.num_sites;
        let dim = 2 * n;
        let mut h = ComplexMatrix::zeros(dim);

        let chi = self.geometry.chirality.sign();
        let t0 = self.hopping_energy_ev;
        let lambda_so = self.spin_orbit_coupling_ev;

        // 1. On-site potential energies:
        for site in 0..n {
            let phi = (site as f64) * self.geometry.twist_angle_rad;
            let v_site = self.on_site_energy_ev + chi * self.chiral_potential_ev * phi.cos();
            h.set(2 * site, 2 * site, Complex::new(v_site, 0.0));
            h.set(2 * site + 1, 2 * site + 1, Complex::new(v_site, 0.0));
        }

        // 2. Nearest-neighbor spin-orbit hopping:
        for site in 0..(n - 1) {
            let omega_hat = self.geometry.spin_orbit_unit_vector(site);
            let (ox, oy, oz) = (omega_hat.x, omega_hat.y, omega_hat.z);

            // Pauli matrix inner product: \boldsymbol{\sigma} \cdot \hat{\boldsymbol{\Omega}}_n
            // = [ [oz, ox - i*oy], [ox + i*oy, -oz] ]
            // Hopping matrix: t_{site, site+1} = -t0 * I - i * lambda_so * (\boldsymbol{\sigma} \cdot \hat{\boldsymbol{\Omega}}_n)
            // t[0, 0] = -t0 - i * lambda_so * oz
            // t[0, 1] = -i * lambda_so * (ox - i*oy) = -lambda_so * oy - i * lambda_so * ox
            // t[1, 0] = -i * lambda_so * (ox + i*oy) =  lambda_so * oy - i * lambda_so * ox
            // t[1, 1] = -t0 + i * lambda_so * oz

            let t_00 = Complex::new(-t0, -lambda_so * oz);
            let t_01 = Complex::new(-lambda_so * oy, -lambda_so * ox);
            let t_10 = Complex::new(lambda_so * oy, -lambda_so * ox);
            let t_11 = Complex::new(-t0, lambda_so * oz);

            let row0 = 2 * site;
            let row1 = 2 * site + 1;
            let col0 = 2 * (site + 1);
            let col1 = 2 * (site + 1) + 1;

            h.set(row0, col0, t_00);
            h.set(row0, col1, t_01);
            h.set(row1, col0, t_10);
            h.set(row1, col1, t_11);

            // Hermitian conjugate t_{site+1, site} = t^\dagger:
            h.set(col0, row0, t_00.conj());
            h.set(col0, row1, t_10.conj());
            h.set(col1, row0, t_01.conj());
            h.set(col1, row1, t_11.conj());
        }

        h
    }

    /// Computes spin-resolved transmission $T_\uparrow(E)$ and $T_\downarrow(E)$ at energy $E$ ($eV$).
    pub fn calculate_transmission(&self, energy_ev: f64) -> CissTransmission {
        let n = self.geometry.num_sites;
        let dim = 2 * n;
        let h = self.build_hamiltonian_matrix();

        let eta = 1e-6; // Infinitesimal imaginary energy
        let gamma_lead = self.contact_coupling_ev;
        let gamma_deph = self.dephasing_rate_ev;

        let omega_hat = self.geometry.spin_orbit_unit_vector(0);
        let axial_ratio = omega_hat.z.abs();
        let chi = self.geometry.chirality.sign();

        let soc_ratio = if self.hopping_energy_ev > 1e-12 {
            (self.spin_orbit_coupling_ev / self.hopping_energy_ev).min(1.0)
        } else {
            0.0
        };

        let n_factor = (self.geometry.num_sites as f64) / 10.0;
        let arg = 3.2 * soc_ratio * axial_ratio * n_factor;
        let alpha = (chi * arg.tanh()).clamp(-0.90, 0.90);

        let gamma_l_up = gamma_lead * (1.0 + alpha);
        let gamma_l_down = gamma_lead * (1.0 - alpha);
        let gamma_r_up = gamma_lead * (1.0 + alpha);
        let gamma_r_down = gamma_lead * (1.0 - alpha);

        // Construct matrix A = (E + i*eta)*I - H - Sigma_L - Sigma_R - Sigma_deph
        let mut a = ComplexMatrix::zeros(dim);
        for r in 0..dim {
            for c in 0..dim {
                let h_rc = h.get(r, c);
                if r == c {
                    let mut diag_im = eta;
                    // Source lead coupling at site 0:
                    if r == 0 {
                        diag_im += 0.5 * gamma_l_up;
                    } else if r == 1 {
                        diag_im += 0.5 * gamma_l_down;
                    }
                    // Drain lead coupling at site N - 1:
                    if r == dim - 2 {
                        diag_im += 0.5 * gamma_r_up;
                    } else if r == dim - 1 {
                        diag_im += 0.5 * gamma_r_down;
                    }
                    // Inelastic dephasing:
                    diag_im += 0.5 * gamma_deph;

                    a.set(r, c, Complex::new(energy_ev - h_rc.re, diag_im));
                } else {
                    a.set(r, c, Complex::new(-h_rc.re, -h_rc.im));
                }
            }
        }

        // Invert A to find retarded Green's function G^R
        let gr = match a.invert() {
            Some(inv) => inv,
            None => {
                return CissTransmission {
                    energy_ev,
                    t_up: 0.0,
                    t_down: 0.0,
                    t_total: 0.0,
                    spin_polarization: 0.0,
                };
            }
        };

        // Lead indices:
        // Source site 0: index 0 (up), index 1 (down)
        // Drain site N-1: index dim-2 (up), index dim-1 (down)
        let g_up_up = gr.get(dim - 2, 0);
        let g_down_up = gr.get(dim - 1, 0);
        let g_up_down = gr.get(dim - 2, 1);
        let g_down_down = gr.get(dim - 1, 1);

        let t_up = (gamma_l_up * gamma_r_up * g_up_up.norm_sq()
            + gamma_l_up * gamma_r_down * g_down_up.norm_sq())
        .min(1.0);
        let t_down = (gamma_l_down * gamma_r_down * g_down_down.norm_sq()
            + gamma_l_down * gamma_r_up * g_up_down.norm_sq())
        .min(1.0);
        let t_total = t_up + t_down;

        let spin_polarization = if t_total > 1e-12 {
            (t_up - t_down) / t_total
        } else {
            0.0
        };

        CissTransmission {
            energy_ev,
            t_up,
            t_down,
            t_total,
            spin_polarization,
        }
    }

    /// Evaluates thermal terminal currents $I_\uparrow$ and $I_\downarrow$ (in Amperes)
    /// across bias $V_{bias}$ ($V$) at temperature $T$ ($K$) via Landauer quadrature:
    /// Returns $(I_\uparrow, I_\downarrow, P_{thermal})$.
    pub fn calculate_thermal_currents(
        &self,
        bias_v: f64,
        temp_k: f64,
        num_points: usize,
    ) -> (f64, f64, f64) {
        let kb_ev = BOLTZMANN_CONSTANT / ELEMENTARY_CHARGE;
        let kt = (kb_ev * temp_k).max(1e-5);

        let mu_l = 0.5 * bias_v;
        let mu_r = -0.5 * bias_v;

        let e_min = (mu_l.min(mu_r) - 6.0 * kt).max(-3.0);
        let e_max = (mu_l.max(mu_r) + 6.0 * kt).min(3.0);
        let de = (e_max - e_min) / (num_points.max(2) as f64);

        let mut i_up = 0.0;
        let mut i_down = 0.0;

        for step in 0..num_points {
            let e = e_min + (step as f64 + 0.5) * de;
            let trans = self.calculate_transmission(e);

            let f_l = 1.0 / (1.0 + ((e - mu_l) / kt).clamp(-60.0, 60.0).exp());
            let f_r = 1.0 / (1.0 + ((e - mu_r) / kt).clamp(-60.0, 60.0).exp());
            let f_diff = f_l - f_r;

            i_up += trans.t_up * f_diff * de;
            i_down += trans.t_down * f_diff * de;
        }

        let prefactor = ELEMENTARY_CHARGE * ELEMENTARY_CHARGE / PLANCK_CONSTANT;
        let current_up = prefactor * i_up;
        let current_down = prefactor * i_down;
        let total_curr = (current_up + current_down).abs();

        let p_th = if total_curr > 1e-18 {
            (current_up - current_down) / (current_up + current_down)
        } else {
            0.0
        };

        (current_up, current_down, p_th)
    }
}
