//! Landau-Lifshitz-Gilbert-Slonczewski (LLGS) Numerical Solver with STT, SOT, and Thermal Langevin Noise.
//!
//! Evaluates the time-dependent micromagnetic magnetization dynamics:
//! \[\frac{d\vec{m}}{dt} = -\frac{\gamma_0}{1 + \alpha^2} \left[ \vec{m} \times \vec{H}_{\text{eff}} + \alpha \vec{m} \times (\vec{m} \times \vec{H}_{\text{eff}}) \right] + \vec{\tau}_{\text{STT}} + \vec{\tau}_{\text{SOT}}\]
//!
//! Features:
//! 1. Precession and damping terms scaled by the Landau-Lifshitz-Gilbert factor.
//! 2. Slonczewski Spin-Transfer Torque (STT) driven by spin-polarized tunneling currents.
//! 3. Spin-Orbit Torque (SOT) generated by the Spin Hall Effect in heavy-metal underlayers (Pt, Ta, W).
//! 4. Brownian stochastic thermal fluctuation field at finite temperature \(T\).
//! 5. Norm-preserving 4th-order Runge-Kutta (RK4) time integration guaranteeing \(|\vec{m}(t)| = 1\).

use crate::spintronics::nanomagnet::{Nanomagnet, Vec3};
use phonon_core::{BOLTZMANN_CONSTANT, ELEMENTARY_CHARGE, H_BAR, MU_0};

/// Physical configuration and spin injection parameters for the LLGS solver.
#[derive(Debug, Clone)]
pub struct LlgsConfig {
    /// Integration time step [s] (typically 0.05 to 0.2 ps)
    pub dt_s: f64,
    /// Operating ambient temperature [K]
    pub temperature_k: f64,
    /// Flag to enable stochastic thermal Langevin field
    pub enable_thermal_noise: bool,
    /// STT spin-polarized current density \(J_e\) [\(\text{A/m}^2\)]
    pub stt_current_density_a_per_m2: f64,
    /// STT spin polarization efficiency factor \(P\) (0.0 to 1.0)
    pub spin_polarization_p: f64,
    /// Fixed polarizing layer magnetization vector \(\vec{m}_p\)
    pub polarizing_layer_m: Vec3,
    /// SOT charge current density \(J_{\text{SOT}}\) [\(\text{A/m}^2\)]
    pub sot_current_density_a_per_m2: f64,
    /// Spin Hall angle \(\theta_{\text{SH}}\) of the heavy metal layer
    pub spin_hall_angle: f64,
    /// SOT spin polarization direction unit vector \(\vec{\sigma}\)
    pub sot_spin_direction: Vec3,
}

impl Default for LlgsConfig {
    fn default() -> Self {
        Self {
            dt_s: 1.0e-13, // 100 fs
            temperature_k: 300.0,
            enable_thermal_noise: false,
            stt_current_density_a_per_m2: 0.0,
            spin_polarization_p: 0.65,
            polarizing_layer_m: Vec3::X,
            sot_current_density_a_per_m2: 0.0,
            spin_hall_angle: 0.30,
            sot_spin_direction: Vec3::Y,
        }
    }
}

/// Numerical solver for Landau-Lifshitz-Gilbert-Slonczewski micromagnetics.
#[derive(Debug, Clone)]
pub struct LlgsSolver {
    pub config: LlgsConfig,
}

impl Default for LlgsSolver {
    fn default() -> Self {
        Self::new(LlgsConfig::default())
    }
}

impl LlgsSolver {
    pub fn new(config: LlgsConfig) -> Self {
        Self { config }
    }

    /// Computes the time derivative \(d\vec{m}/dt\) given current magnetization \(\vec{m}\) and effective field \(\vec{H}_{\text{eff}}\).
    pub fn compute_dmdt(
        &self,
        m: Vec3,
        h_eff: Vec3,
        magnet: &Nanomagnet,
        thermal_field: Vec3,
    ) -> Vec3 {
        let alpha = magnet.material.alpha;
        let gamma_0 = magnet.material.gamma_0; // rad/(s T)
        let factor = -gamma_0 / (1.0 + alpha * alpha);

        // Convert H_eff [A/m] to B_eff [Tesla] = mu_0 * H_eff
        let h_total = h_eff.add(thermal_field);
        let b_total = h_total.scale(MU_0);

        // Precession: m x B
        let m_cross_b = m.cross(b_total);

        // Gilbert damping: m x (m x B)
        let damping = m.cross(m_cross_b);

        // LLG base term = factor * [ (m x B) + alpha * (m x (m x B)) ]
        let llg_term = m_cross_b.add(damping.scale(alpha)).scale(factor);

        // STT torque: tau_STT = - (gamma_0 * hbar * J * P) / (2 * e * M_s * t) * [ m x (m x m_p) ]
        let stt_term = if self.config.stt_current_density_a_per_m2.abs() > 1.0e-6 {
            let j_e = self.config.stt_current_density_a_per_m2;
            let p = self.config.spin_polarization_p;
            let ms = magnet.material.ms_a_per_m;
            let t = magnet.thickness_m;

            let tau_stt = (gamma_0 * H_BAR * j_e * p) / (2.0 * ELEMENTARY_CHARGE * ms * t);
            let m_cross_mp = m.cross(self.config.polarizing_layer_m.normalize());
            let m_cross_m_cross_mp = m.cross(m_cross_mp);
            m_cross_m_cross_mp.scale(-tau_stt)
        } else {
            Vec3::ZERO
        };

        // SOT torque: tau_SOT = - (gamma_0 * hbar * theta_SH * J_SOT) / (2 * e * M_s * t) * [ m x (m x sigma) ]
        let sot_term = if self.config.sot_current_density_a_per_m2.abs() > 1.0e-6 {
            let j_sot = self.config.sot_current_density_a_per_m2;
            let theta_sh = self.config.spin_hall_angle;
            let ms = magnet.material.ms_a_per_m;
            let t = magnet.thickness_m;

            let tau_sot = (gamma_0 * H_BAR * theta_sh * j_sot) / (2.0 * ELEMENTARY_CHARGE * ms * t);
            let m_cross_sigma = m.cross(self.config.sot_spin_direction.normalize());
            let m_cross_m_cross_sigma = m.cross(m_cross_sigma);
            m_cross_m_cross_sigma.scale(-tau_sot)
        } else {
            Vec3::ZERO
        };

        llg_term.add(stt_term).add(sot_term)
    }

    /// Evaluates the stochastic thermal fluctuation field magnitude \(\sigma_{\text{th}}\) [A/m].
    pub fn compute_thermal_field_magnitude(&self, magnet: &Nanomagnet) -> f64 {
        if !self.config.enable_thermal_noise || self.config.temperature_k <= 0.0 {
            return 0.0;
        }

        let alpha = magnet.material.alpha;
        let gamma_0 = magnet.material.gamma_0;
        let ms = magnet.material.ms_a_per_m;
        let vol = magnet.volume();
        let dt = self.config.dt_s;

        // sigma^2 = (2 * alpha * k_B * T) / (gamma_0 * mu_0 * M_s * V * dt)
        let num = 2.0 * alpha * BOLTZMANN_CONSTANT * self.config.temperature_k;
        let den = gamma_0 * MU_0 * ms * vol * dt;

        (num / den.max(1.0e-30)).sqrt()
    }

    /// Advances the magnetization of a nanomagnet by one time step using 4th-order Runge-Kutta (RK4).
    ///
    /// Preserves \(|\vec{m}| = 1\) through normalization at the conclusion of the RK4 stage.
    pub fn step_rk4(&self, magnet: &mut Nanomagnet, h_external: Vec3, thermal_field: Vec3) {
        let dt = self.config.dt_s;
        let m0 = magnet.m;

        // Effective field helper function at state m
        let calc_heff = |m_eval: Vec3| -> Vec3 {
            let mut temp = magnet.clone();
            temp.m = m_eval.normalize();
            let h_demag = temp.compute_demag_field();
            let h_ani = temp.compute_anisotropy_field();
            h_external.add(h_demag).add(h_ani)
        };

        // k1
        let h1 = calc_heff(m0);
        let k1 = self.compute_dmdt(m0, h1, magnet, thermal_field);

        // k2
        let m1 = m0.add(k1.scale(dt * 0.5)).normalize();
        let h2 = calc_heff(m1);
        let k2 = self.compute_dmdt(m1, h2, magnet, thermal_field);

        // k3
        let m2 = m0.add(k2.scale(dt * 0.5)).normalize();
        let h3 = calc_heff(m2);
        let k3 = self.compute_dmdt(m2, h3, magnet, thermal_field);

        // k4
        let m3 = m0.add(k3.scale(dt)).normalize();
        let h4 = calc_heff(m3);
        let k4 = self.compute_dmdt(m3, h4, magnet, thermal_field);

        // RK4 update: m = m0 + (dt / 6) * (k1 + 2*k2 + 2*k3 + k4)
        let sum_k = k1.add(k2.scale(2.0)).add(k3.scale(2.0)).add(k4);
        let m_new = m0.add(sum_k.scale(dt / 6.0));

        // Enforce strict magnetic norm conservation
        magnet.m = m_new.normalize();
    }

    /// Simulates magnetization trajectory for a specified total duration [s].
    pub fn simulate_trajectory(
        &self,
        magnet: &mut Nanomagnet,
        h_external: Vec3,
        total_time_s: f64,
    ) -> Vec<(f64, Vec3)> {
        let num_steps = (total_time_s / self.config.dt_s).ceil() as usize;
        let mut history = Vec::with_capacity(num_steps + 1);
        history.push((0.0, magnet.m));

        let thermal = Vec3::ZERO; // Deterministic trajectory if called without random seed

        for step in 1..=num_steps {
            self.step_rk4(magnet, h_external, thermal);
            let t = (step as f64) * self.config.dt_s;
            history.push((t, magnet.m));
        }

        history
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::spintronics::nanomagnet::MagneticMaterial;

    #[test]
    fn test_llgs_norm_conservation_under_precession() {
        let mut mat = MagneticMaterial::cofeb();
        mat.alpha = 0.08; // Higher damping for rapid test convergence
        let mut magnet = Nanomagnet::new_rectangular(
            1,
            Vec3::ZERO,
            60.0e-9,
            30.0e-9,
            3.0e-9,
            mat,
            Vec3::X,
            Vec3::new(0.6, 0.8, 0.0), // Perturbed from easy axis
        );

        let solver = LlgsSolver::new(LlgsConfig {
            dt_s: 2.0e-13, // 0.2 ps
            ..Default::default()
        });

        // Run 1500 steps (300 ps of precession and damping towards external field + anisotropy)
        let h_ext = Vec3::new(2.0e5, 0.0, 0.0); // 200 kA/m external bias along +X
        for _ in 0..1500 {
            solver.step_rk4(&mut magnet, h_ext, Vec3::ZERO);
            let norm = magnet.m.norm();
            assert!(
                (norm - 1.0).abs() < 1.0e-9,
                "Magnetization norm must remain strictly 1.0, got {:.12}",
                norm
            );
        }

        // Magnet should relax towards +X easy axis
        assert!(
            magnet.m.x > 0.90,
            "Magnet must damp towards +X easy axis, got m.x = {:.4}",
            magnet.m.x
        );
    }

    #[test]
    fn test_stt_magnetization_switching() {
        let mut mat = MagneticMaterial::cofeb();
        mat.alpha = 0.05;
        let mut magnet = Nanomagnet::new_rectangular(
            1,
            Vec3::ZERO,
            50.0e-9,
            25.0e-9,
            2.5e-9,
            mat,
            Vec3::X,
            Vec3::new(-0.98, 0.19, 0.0), // Initially anti-parallel (-X)
        );

        // Apply STT spin current polarized along +X to switch magnetization from -X to +X
        let solver = LlgsSolver::new(LlgsConfig {
            dt_s: 1.0e-13,                        // 100 fs
            stt_current_density_a_per_m2: 3.5e12, // High spin current density exceeding J_c
            spin_polarization_p: 0.80,
            polarizing_layer_m: Vec3::X,
            ..Default::default()
        });

        // Run 3000 steps (300 ps)
        for _ in 0..3000 {
            solver.step_rk4(&mut magnet, Vec3::ZERO, Vec3::ZERO);
        }

        // Magnetization should have switched to +X
        assert!(
            magnet.m.x > 0.70,
            "STT torque must reverse magnetization to +X, got m.x = {:.4}",
            magnet.m.x
        );
    }
}
